"""Removed null constraint on  a few column for User model and roles model.

Revision ID: 2e1908bdd61c
Revises: 83cf16dbb1e6
Create Date: 2024-07-18 19:29:15.345062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e1908bdd61c'
down_revision = '83cf16dbb1e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('created_on',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('created_on',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
