"""Removed null constraints column from Visit model.

Revision ID: 30cd3da4b52a
Revises: 1dc88fbe6836
Create Date: 2024-07-18 21:40:20.052467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30cd3da4b52a'
down_revision = '1dc88fbe6836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('exit_time',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('response',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('reschedule_date',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('cancellation_reason',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.alter_column('cancellation_reason',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('reschedule_date',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('response',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('exit_time',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    # ### end Alembic commands ###
