"""empty message

Revision ID: 83cf16dbb1e6
Revises: 4beb899b432d
Create Date: 2024-07-18 19:18:59.503777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83cf16dbb1e6'
down_revision = '4beb899b432d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('updated_by',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('last_updated',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('updated_by',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('last_updated',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    # ### end Alembic commands ###
