"""empty message

Revision ID: edcf263694f1
Revises: 
Create Date: 2024-08-05 14:47:57.099246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edcf263694f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=30), nullable=False),
    sa.Column('created_on', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.String(length=30), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.Column('delete_yn', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('contact_method', sa.String(length=10), nullable=False),
    sa.Column('contact', sa.String(length=50), nullable=False),
    sa.Column('staff_name', sa.String(length=50), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('multiple_visitors', sa.Boolean(), nullable=True),
    sa.Column('number_of_visitors', sa.Integer(), nullable=True),
    sa.Column('entry_time', sa.String(length=30), nullable=False),
    sa.Column('exit_time', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('response', sa.String(length=30), nullable=True),
    sa.Column('reschedule_date', sa.String(length=30), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=30), nullable=True),
    sa.Column('delete_yn', sa.String(length=1), nullable=False),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.String(length=30), nullable=False),
    sa.Column('last_updated', sa.String(length=30), nullable=True),
    sa.Column('updated_by', sa.String(length=30), nullable=True),
    sa.Column('delete_yn', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_user_role'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('visit')
    op.drop_table('roles')
    # ### end Alembic commands ###
